version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres_container_polL_system
    environment:
      POSTGRES_DB: poll_system_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
